# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updatedata.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(352, 163)
        Form.setStyleSheet("#Form{\n"
"    background-color: qconicalgradient(cx:0.045, cy:0, angle:135, stop:0 rgba(30, 0, 255, 255), stop:0.375 rgba(0, 195, 255, 252), stop:0.423533 rgba(37, 0, 255, 255), stop:0.45 rgba(0, 130, 255, 255), stop:0.477581 rgba(0, 56, 255, 252), stop:0.518717 rgba(71, 171, 255, 255), stop:0.542289 rgba(71, 171, 255, 255), stop:0.547264 rgba(68, 134, 249, 255), stop:0.55 rgba(0, 74, 255, 255), stop:0.552239 rgba(21, 93, 243, 255), stop:0.57754 rgba(102, 0, 255, 255), stop:0.625 rgba(0, 185, 255, 247), stop:1 rgba(255, 255, 0, 69));\n"
"}\n"
"QLineEdit{\n"
"border-radius:10px;\n"
"border-bottom:3px solid green;\n"
"color:#000000;\n"
"}\n"
"QPushButton{\n"
"border-radius:10px;\n"
"border:3px solid green;\n"
"color:#000000;\n"
"}")
        self.Password = QtWidgets.QLineEdit(Form)
        self.Password.setGeometry(QtCore.QRect(117, 88, 211, 22))
        self.Password.setObjectName("Password")
        self.Ok_btn = QtWidgets.QPushButton(Form)
        self.Ok_btn.setGeometry(QtCore.QRect(227, 128, 93, 28))
        self.Ok_btn.setObjectName("Ok_btn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(14, 29, 91, 20))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 89, 71, 20))
        self.label_3.setObjectName("label_3")
        self.Website = QtWidgets.QLineEdit(Form)
        self.Website.setGeometry(QtCore.QRect(117, 29, 211, 21))
        self.Website.setObjectName("Website")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(36, 57, 71, 20))
        self.label_2.setObjectName("label_2")
        self.Username = QtWidgets.QLineEdit(Form)
        self.Username.setGeometry(QtCore.QRect(117, 58, 211, 22))
        self.Username.setObjectName("Username")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Ok_btn.setText(_translate("Form", "OK"))
        self.label.setText(_translate("Form", "From Website :"))
        self.label_3.setText(_translate("Form", "Password :"))
        self.label_2.setText(_translate("Form", "Username :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_update()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
